# Site settings
title: Protocol Painting
email: info@protocolpainting.com
description: >-
  Professional painting services for residential and commercial clients in Bellingham, WA.
  Quality interior and exterior painting with exceptional customer service.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
phone: "+13609208423"
phone_display: "360-920-8423"
address: "Bellingham, WA"
owner: "Dominick Pazo"

# Social media
social:
  facebook: "https://facebook.com/protocolpainting"
  instagram: "https://instagram.com/protocolpainting"
  linkedin: "https://linkedin.com/company/protocolpainting"
  google: "https://g.page/protocolpainting"
  yelp: "https://yelp.com/biz/protocolpainting"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  services:
    output: true
  team:
    output: true
  testimonials:
    output: false
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - LICENSE.txt
  - READ-ME.txt